# Generated by Django 4.2.7 on 2023-11-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(upload_to='pics')),
                ('Name', models.CharField(max_length=250)),
                ('Desc', models.TextField()),
            ],
        ),
    ]
